version: '3'

services:
  zk1:
    image: zookeeper
    container_name: zk1
    restart: unless-stopped
    hostname: zk1
    ports:
      - "22181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:22888:23888 server.2=zk2:22888:23888 server.3=zk3:22888:23888
    volumes:
       - "/etc/localtime:/etc/localtime:ro"

  zk2:
    image: zookeeper
    container_name: zk2
    restart: unless-stopped
    hostname: zk2
    ports:
      - "22182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:22888:23888 server.2=0.0.0.0:22888:23888 server.3=zk3:22888:23888
    volumes:
       - "/etc/localtime:/etc/localtime:ro"

  zk3:
    image: zookeeper
    container_name: zk3
    restart: unless-stopped
    hostname: zk3
    ports:
      - "22183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:22888:23888 server.2=zk2:22888:23888 server.3=0.0.0.0:22888:23888
    volumes:
       - "/etc/localtime:/etc/localtime:ro"

networks:
  default:
    external:
      name: zk-net