filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/user/elk/logs/*.log
  multiline:
      pattern: ^\d{4}
      negate: true
      match: after
  fields:
      doc_type: business
output.logstash: # 输出地址
  hosts: ["logstash:5043"]