version: '3'

services:
  kafka-zk:
    image: zookeeper
    container_name: kafka-zk
    restart: unless-stopped
    hostname: kafka-zk
    ports:
      - "2181"
    volumes:
       - "/etc/localtime:/etc/localtime:ro"

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka
    hostname: kafka1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_VERSION: 1.1.0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zk:2181
    depends_on:
      - kafka-zk

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka
    hostname: kafka2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    ports:
      - 9093:9092
    environment:
      KAFKA_VERSION: 1.1.0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zk:2181
    depends_on:
      - kafka-zk

  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka
    hostname: kafka3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    ports:
      - 9094:9092
    environment:
      KAFKA_VERSION: 1.1.0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zk:2181
    depends_on:
      - kafka-zk

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:1.3.3.18
    volumes:
      - "/home/docker/kafka/manager/conf:/kafka-manager/conf"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    ports:
      - 9892:9000
    command: -Dpidfile.path=/dev/null -Dapplication.home=/kafka-manager
    environment:
      APPLICATION_SECRET: "random-secret"
      ZK_HOSTS: "kafka-zk:2181"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

networks:
    default:
        external:
            name: bigdata-net